version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/caster-back"
    schedule:
      interval: "monthly"
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/caster-front"
    schedule:
      interval: "monthly"
    target-branch: "main"
  - package-ecosystem: "npm"
    directory: "/caster-editor"
    schedule:
      interval: "monthly"
    target-branch: "main"
