services:
  editor:
    platform: linux/amd64
    build:
      context: caster-editor
      dockerfile: Dockerfile.deploy
      args:
        - BACKEND_URL=http://127.0.0.1:8081
    ports:
      - 3001:3001
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - BACKEND_URL=http://127.0.0.1:8081
