FROM node:19-alpine AS builder

WORKDIR /root/caster-front

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

ARG BACKEND_URL
ARG JANUS_URL
ARG SENTRY_DSN_CASTER_FRONT

ENV VITE_BACKEND_URL=${BACKEND_URL}
ENV VITE_JANUS_URL=${JANUS_URL}
ENV VITE_SENTRY_DSN_CASTER_FRONT=${SENTRY_DSN_CASTER_FRONT}

RUN npm run build

FROM nginx:1.23-alpine

COPY --from=builder /root/caster-front/dist/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
