FROM node:14-alpine AS builder

WORKDIR /root/caster-front

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY . .

ARG BACKEND_GRAPHQL_URL
ARG JANUS_URL

ENV VITE_BACKEND_GRAPHQL_URL=${BACKEND_GRAPHQL_URL}
ENV VITE_JANUS_URL=${JANUS_URL}

RUN npm run build

FROM nginx:1.23-alpine

COPY --from=builder /root/caster-front/dist/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
