FROM node:18-alpine

WORKDIR /root/caster-editor

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY src/ /root/caster-editor/src/

ARG BACKEND_GRAPHQL_URL

ENV BACKEND_GRAPHQL_URL=${BACKEND_GRAPHQL_URL}

RUN npm run build

CMD ["node", "./dist/index.mjs"]
