FROM node:18-alpine AS builder

WORKDIR /root/caster-editor

COPY package.json .
COPY package-lock.json .

RUN npm ci

COPY src/ /root/caster-editor/src/

ARG BACKEND_URL

ENV VITE_BACKEND_URL=${BACKEND_URL}

ADD . .

RUN npm run build

FROM nginx:1.23-alpine

COPY --from=builder /root/caster-editor/dist/ /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
