query MyQuery {
  graphs {
    name
  }
}

query testQuery {
  graphs {
    nodes {
      name
    }
    edges {
      uuid
    }
    name
  }
}

query GetGraphs {
  graphs {
    uuid
    name
  }
}

query getGraph($uuid: ID) {
  graph(pk: $uuid) {
    name
    uuid
    edges {
      uuid
      outNode {
        uuid
      }
      inNode {
        uuid
      }
    }
    nodes {
      name
      uuid
      scriptCells {
        cellCode
        cellOrder
        cellType
        uuid
      }
      positionX
      positionY
      color
    }
  }
}

query getNode($nodeUuid: ID!) {
  node(pk: $nodeUuid) {
    color
    name
    positionX
    positionY
    scriptCells {
      cellCode
      cellOrder
      cellType
      uuid
    }
    uuid
  }
}

mutation createEdge($nodeInUuid:UUID!, $nodeOutUuid:UUID!) {
  addEdge(newEdge: {nodeInUuid: $nodeInUuid, nodeOutUuid: $nodeOutUuid})
}

mutation createNode($name: String!, $graphUuid: UUID!, $color: String, $positionX: Float, $positionY: Float) {
  addNode(
    newNode: {name: $name, graphUuid: $graphUuid, color: $color, positionX: $positionX, positionY: $positionY}
  )
}

mutation updateNode($nodeUuid: UUID!, $name: String, $color: String, $positionX: Float, $positionY: Float) {
  updateNode(
    nodeUpdate: {uuid: $nodeUuid, name: $name, color: $color, positionX: $positionX, positionY: $positionY}
  )
}

mutation deleteNode($nodeUuid: UUID!) {
  deleteNode(nodeUuid: $nodeUuid)
}

mutation deleteEdge($edgeUuid: UUID!) {
  deleteEdge(edgeUuid: $edgeUuid)
}

mutation createScriptCell($nodeUuid: UUID!, $order: Int!) {
  addScriptCell(nodeUuid: $nodeUuid, order: $order) {
    cellOrder
    uuid
    cellType
    cellCode
  }
}

mutation deleteScriptCell($scriptCellUuid:UUID!) {
  deleteScriptCell(scriptCellUuid: $scriptCellUuid)
}

# script cells get updated according to the uuid field
mutation updateScriptCells($newCells: [ScriptCellInput!]!) {
  updateScriptCells(newCells: $newCells)
}

query GetStream {
  getStream {
    active
    modifiedDate
    uuid
    streamPoint {
      host
      createdDate
      janusInPort
      janusOutPort
      lastLive
      modifiedDate
      port
      useInput
      uuid
    }
    createdDate
  }
}
