query GetGraphs {
  graphs {
    uuid
    name
  }
}

mutation createEdge($nodeInUuid:UUID!, $nodeOutUuid:UUID!) {
  addEdge(newEdge: {nodeInUuid: $nodeInUuid, nodeOutUuid: $nodeOutUuid})
}

mutation createNode($name: String!, $graphUuid: UUID!, $color: String, $positionX: Float, $positionY: Float) {
  addNode(
    newNode: {name: $name, graphUuid: $graphUuid, color: $color, positionX: $positionX, positionY: $positionY}
  )
}

mutation updateNode($nodeUuid: UUID!, $name: String, $color: String, $positionX: Float, $positionY: Float) {
  updateNode(
    nodeUpdate: {uuid: $nodeUuid, name: $name, color: $color, positionX: $positionX, positionY: $positionY}
  )
}

mutation deleteNode($nodeUuid: UUID!) {
  deleteNode(nodeUuid: $nodeUuid)
}

mutation deleteEdge($edgeUuid: UUID!) {
  deleteEdge(edgeUuid: $edgeUuid)
}

mutation createScriptCell($nodeUuid: UUID!, $newScriptCell: NewScriptCellInput!) {
  addScriptCell(nodeUuid: $nodeUuid, newScriptCell: $newScriptCell) {
    cellOrder
    uuid
    cellType
    cellCode
  }
}

mutation deleteScriptCell($scriptCellUuid:UUID!) {
  deleteScriptCell(scriptCellUuid: $scriptCellUuid)
}

# script cells get updated according to the uuid field
mutation updateScriptCells($newCells: [ScriptCellInput!]!) {
  updateScriptCells(newCells: $newCells)
}

subscription CountSubscription {
  count
}

subscription graph($uuid: UUID!) {
  graph(graphUuid: $uuid) {
    name
    uuid
    edges {
      uuid
      outNode {
        uuid
      }
      inNode {
        uuid
      }
    }
    nodes {
      name
      uuid
      scriptCells {
        cellCode
        cellOrder
        cellType
        uuid
      }
      positionX
      positionY
      color
    }
  }
}

subscription node($uuid: UUID!) {
  node(nodeUuid: $uuid) {
    color
    name
    positionX
    positionY
    scriptCells {
      cellCode
      cellOrder
      cellType
      uuid
    }
    uuid
  }
}

subscription stream {
  streamInfo {
    stream {
      active
      createdDate
      modifiedDate
      streamPoint {
        createdDate
        host
        janusInPort
        janusInRoom
        janusOutPort
        janusOutRoom
        lastLive
        modifiedDate
        port
        uuid
        useInput
      }
      uuid
    }
    streamInstruction {
      createdDate
      instructionText
      modifiedDate
      returnValue
      state
      uuid
    }
  }
}

query streamPoints {
  streamPoints {
    createdDate
    host
    janusInPort
    janusInRoom
    janusOutPort
    janusOutRoom
    lastLive
    modifiedDate
    port
    useInput
    uuid
  }
}
