# Generated by Django 4.0.2 on 2022-03-08 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TextToSpeech",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.TextField(
                        default="<speak>Hallo Welt</speak>",
                        editable=False,
                        max_length=5000,
                        verbose_name="Input text in SSML format",
                    ),
                ),
                (
                    "voice_name",
                    models.CharField(
                        choices=[
                            ("de-DE-Standard-A", "de-DE-Standard-A__FEMALE"),
                            ("de-DE-Standard-B", "de-DE-Standard-B__MALE"),
                            ("de-DE-Standard-C", "de-DE-Standard-C__FEMALE"),
                            ("de-DE-Standard-D", "de-DE-Standard-D__MALE"),
                            ("de-DE-Standard-E", "de-DE-Standard-E__MALE"),
                            ("de-DE-Standard-F", "de-DE-Standard-F__FEMALE"),
                            ("de-DE-Wavenet-A", "de-DE-Wavenet-A__FEMALE"),
                            ("de-DE-Wavenet-B", "de-DE-Wavenet-B__MALE"),
                            ("de-DE-Wavenet-C", "de-DE-Wavenet-C__FEMALE"),
                            ("de-DE-Wavenet-D", "de-DE-Wavenet-D__MALE"),
                            ("de-DE-Wavenet-E", "de-DE-Wavenet-E__MALE"),
                            ("de-DE-Wavenet-F", "de-DE-Wavenet-F__FEMALE"),
                        ],
                        default="de-DE-Standard-D",
                        max_length=64,
                        verbose_name="Name of voice used to generate",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="speech_to_text/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text to speech job",
                "verbose_name_plural": "Text to speech jobs",
            },
        ),
    ]
