# Generated by Django 4.0.2 on 2022-03-16 10:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Is stream currently in use"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream",
                "verbose_name_plural": "Streams",
                "ordering": ["-created_date", "stream_point"],
            },
        ),
        migrations.CreateModel(
            name="StreamPoint",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.CharField(max_length=255, verbose_name="SuperCollider host"),
                ),
                ("port", models.IntegerField(verbose_name="SuperCollider port")),
                (
                    "last_live",
                    models.DateTimeField(
                        null=True,
                        verbose_name="Last live signal from SuperCollider server",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream Endpoint",
                "verbose_name_plural": "Stream Endpoints",
                "ordering": ["-last_live", "host", "port"],
                "unique_together": {("host", "port")},
            },
        ),
        migrations.CreateModel(
            name="StreamInstruction",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "instruction_text",
                    models.TextField(
                        verbose_name="Instruction that gets transmitted via OSC"
                    ),
                ),
                ("acknowledged_time", models.DateTimeField()),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="stream.stream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream Instruction",
                "verbose_name_plural": "Stream Instructions",
                "ordering": ["-created_date", "stream"],
            },
        ),
        migrations.AddField(
            model_name="stream",
            name="stream_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="stream.streampoint",
                verbose_name="Associated instance",
            ),
        ),
    ]
