# Generated by Django 4.0.2 on 2022-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="streampoint",
            name="janus_in_port",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="RTP port where Janus streams the audio its received from user",
            ),
        ),
        migrations.AddField(
            model_name="streampoint",
            name="janus_in_room",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Audiobridge room ID under which Janus can send audio to SuperCollider",
            ),
        ),
        migrations.AddField(
            model_name="streampoint",
            name="janus_out_port",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="RTP port where SuperCollider/gstreamer streams its audio to Janus",
            ),
        ),
        migrations.AddField(
            model_name="streampoint",
            name="janus_out_room",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Streaming room ID under which Janus serves audio from SuperCollider",
            ),
        ),
        migrations.AddField(
            model_name="streampoint",
            name="janus_public_ip",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="IP or Hostname under which the janus instance is reachable",
            ),
        ),
        migrations.AddField(
            model_name="streampoint",
            name="sc_name",
            field=models.CharField(
                max_length=128,
                null=True,
                verbose_name="Internal name of the SuperCollider instance on the host, necessary for gstreamer",
            ),
        ),
        migrations.AddField(
            model_name="streampoint",
            name="use_input",
            field=models.BooleanField(
                default=False, verbose_name="Accepts to send audio input"
            ),
        ),
    ]
