# Generated by Django 4.1.3 on 2022-11-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0003_alter_streampoint_janus_in_port_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="streaminstruction",
            options={
                "ordering": ["-created_date", "stream_point"],
                "verbose_name": "Stream Instruction",
                "verbose_name_plural": "Stream Instructions",
            },
        ),
        migrations.RemoveField(
            model_name="streaminstruction",
            name="acknowledged_time",
        ),
        migrations.RemoveField(
            model_name="streaminstruction",
            name="stream",
        ),
        migrations.AddField(
            model_name="streaminstruction",
            name="state",
            field=models.TextField(
                choices=[
                    ("SUCCESS", "SUCCESS"),
                    ("FAILURE", "FAILURE"),
                    ("READY", "READY"),
                    ("SENT", "SENT"),
                    ("UNACKNOWLEDGED", "UNACKNOWLEDGED"),
                    ("FINISHED", "FINISHED"),
                    ("RECEIVED", "RECEIVED"),
                ],
                default="UNACKNOWLEDGED",
                max_length=100,
                verbose_name="Instruction state",
            ),
        ),
        migrations.AddField(
            model_name="streaminstruction",
            name="stream_point",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructions",
                to="stream.streampoint",
            ),
        ),
    ]
