# Generated by Django 4.1.3 on 2022-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0004_alter_streaminstruction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streaminstruction",
            name="return_value",
            field=models.TextField(
                blank=True, default="", verbose_name="Return value from statement"
            ),
        ),
    ]
