# Generated by Django 4.1.3 on 2022-11-15 21:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0005_streaminstruction_return_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="audio_files"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Additional description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio file",
                "verbose_name_plural": "Audio files",
            },
        ),
        migrations.AlterModelOptions(
            name="streaminstruction",
            options={
                "ordering": ["-modified_date", "stream_point"],
                "verbose_name": "Stream Instruction",
                "verbose_name_plural": "Stream Instructions",
            },
        ),
        migrations.AlterField(
            model_name="streaminstruction",
            name="return_value",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                verbose_name="Return value from statement",
            ),
        ),
        migrations.AlterField(
            model_name="streaminstruction",
            name="state",
            field=models.TextField(
                choices=[
                    ("SUCCESS", "SUCCESS"),
                    ("FAILURE", "FAILURE"),
                    ("READY", "READY"),
                    ("SENT", "SENT"),
                    ("UNACKNOWLEDGED", "UNACKNOWLEDGED"),
                    ("FINISHED", "FINISHED"),
                    ("RECEIVED", "RECEIVED"),
                ],
                default="UNACKNOWLEDGED",
                editable=False,
                max_length=100,
                verbose_name="Instruction state",
            ),
        ),
        migrations.CreateModel(
            name="TextToSpeech",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "text",
                    models.TextField(
                        default="<speak>Hallo Welt</speak>",
                        editable=False,
                        max_length=5000,
                        verbose_name="Input text in SSML format",
                    ),
                ),
                (
                    "voice_name",
                    models.CharField(
                        choices=[
                            ("de-DE-Standard-A", "de-DE-Standard-A__FEMALE"),
                            ("de-DE-Standard-B", "de-DE-Standard-B__MALE"),
                            ("de-DE-Standard-C", "de-DE-Standard-C__FEMALE"),
                            ("de-DE-Standard-D", "de-DE-Standard-D__MALE"),
                            ("de-DE-Standard-E", "de-DE-Standard-E__MALE"),
                            ("de-DE-Standard-F", "de-DE-Standard-F__FEMALE"),
                            ("de-DE-Wavenet-A", "de-DE-Wavenet-A__FEMALE"),
                            ("de-DE-Wavenet-B", "de-DE-Wavenet-B__MALE"),
                            ("de-DE-Wavenet-C", "de-DE-Wavenet-C__FEMALE"),
                            ("de-DE-Wavenet-D", "de-DE-Wavenet-D__MALE"),
                            ("de-DE-Wavenet-E", "de-DE-Wavenet-E__MALE"),
                            ("de-DE-Wavenet-F", "de-DE-Wavenet-F__FEMALE"),
                        ],
                        default="de-DE-Standard-D",
                        max_length=64,
                        verbose_name="Name of voice used to generate",
                    ),
                ),
                (
                    "audio_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stream.audiofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text to speech job",
                "verbose_name_plural": "Text to speech jobs",
            },
        ),
    ]
