# Generated by Django 4.1.3 on 2023-03-13 17:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0008_delete_graphsession"),
        ("stream", "0006_audiofile_alter_streaminstruction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="graph",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="story_graph.graph",
            ),
        ),
        migrations.CreateModel(
            name="StreamVariable",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=512)),
                ("value", models.TextField(default="")),
                (
                    "stream_to_sc",
                    models.BooleanField(
                        default=False,
                        help_text="Stream values to SC as control rate Ndef",
                        verbose_name="Stream to SuperCollider",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="stream.stream",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="StreamVariable",
            constraint=models.UniqueConstraint(
                fields=("stream", "key"), name="unique key within graph session"
            ),
        ),
    ]
