# Generated by Django 4.1.3 on 2023-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0008_audiofile_auto_generated_audiofile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stream",
            name="active",
        ),
        migrations.AddField(
            model_name="stream",
            name="num_listeners",
            field=models.IntegerField(
                default=0,
                help_text="Used as a garbage collection. If multiple users share the same stream we need to know when we can release the stream which happens if listener counter is 0. It starts with a default of 0 because this allows us to count stateless.",
                verbose_name="Number of listeners",
            ),
        ),
    ]
