# Generated by Django 4.1.3 on 2023-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0009_remove_stream_active_stream_num_listeners"),
    ]

    operations = [
        migrations.AlterField(
            model_name="texttospeech",
            name="voice_name",
            field=models.CharField(
                choices=[
                    ("de-DE-Standard-A", "de-DE-Standard-A__FEMALE"),
                    ("de-DE-Standard-B", "de-DE-Standard-B__MALE"),
                    ("de-DE-Standard-C", "de-DE-Standard-C__FEMALE"),
                    ("de-DE-Standard-D", "de-DE-Standard-D__MALE"),
                    ("de-DE-Standard-E", "de-DE-Standard-E__MALE"),
                    ("de-DE-Standard-F", "de-DE-Standard-F__FEMALE"),
                    ("de-DE-Wavenet-A", "de-DE-Wavenet-A__FEMALE"),
                    ("de-DE-Wavenet-B", "de-DE-Wavenet-B__MALE"),
                    ("de-DE-Wavenet-C", "de-DE-Wavenet-C__FEMALE"),
                    ("de-DE-Wavenet-D", "de-DE-Wavenet-D__MALE"),
                    ("de-DE-Wavenet-E", "de-DE-Wavenet-E__MALE"),
                    ("de-DE-Wavenet-F", "de-DE-Wavenet-F__FEMALE"),
                    ("de-DE-Neural2-B", "de-DE-Neural2-B__MALE"),
                    ("de-DE-Neural2-C", "de-DE-Neural2-C__FEMALE"),
                    ("de-DE-Neural2-D", "de-DE-Neural2-D__MALE"),
                    ("de-DE-Neural2-F", "de-DE-Neural2-F__FEMALE"),
                    ("de-DE-Polyglot-1", "de-DE-Polyglot-1__MALE"),
                ],
                default="de-DE-Neural2-C",
                max_length=64,
                verbose_name="Name of voice used to generate",
            ),
        ),
    ]
