# Generated by Django 4.1.3 on 2023-07-31 15:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stream", "0010_alter_texttospeech_voice_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamLog",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "origin",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("graph_engine", "Graph engine"),
                            ("supercollider", "SuperCollider"),
                            ("janus", "Janus"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (50, "Critical"),
                            (40, "Error"),
                            (30, "Warning"),
                            (20, "Info"),
                            (10, "Debug"),
                            (0, "Not set"),
                        ],
                        default=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("name", models.TextField(blank=True, null=True)),
                (
                    "stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stream.stream",
                    ),
                ),
                (
                    "stream_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stream.streampoint",
                    ),
                ),
            ],
        ),
    ]
