# Generated by Django 4.0.2 on 2022-09-30 13:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stream", "0003_alter_streampoint_janus_in_port_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the graph",
                        max_length=255,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Graph",
                "verbose_name_plural": "Graphs",
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="Name of the node",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="story_graph.graph",
                    ),
                ),
            ],
            options={
                "ordering": ["graph"],
            },
        ),
        migrations.CreateModel(
            name="GraphSession",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_sessions",
                        to="story_graph.graph",
                    ),
                ),
                (
                    "streaming_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_sessions",
                        to="stream.streampoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "in_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="story_graph.node",
                    ),
                ),
                (
                    "out_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="story_graph.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScriptCell",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "cell_type",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("python", "Python"),
                            ("supercollider", "SuperCollider"),
                            ("comment", "Comment"),
                        ],
                        max_length=128,
                        verbose_name="Cell type",
                    ),
                ),
                ("cell_code", models.TextField(verbose_name="Cell code")),
                ("cell_order", models.IntegerField(default=0)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_cells",
                        to="story_graph.node",
                    ),
                ),
            ],
            options={
                "ordering": ["node", "cell_order"],
                "unique_together": {("cell_order", "node")},
            },
        ),
    ]
