# Generated by Django 4.0.2 on 2022-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="edge",
            constraint=models.UniqueConstraint(
                fields=("in_node", "out_node"), name="unique_edge"
            ),
        ),
    ]
