# Generated by Django 4.1.3 on 2022-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0002_unique_edges"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="color",
            field=models.CharField(
                default="#fff",
                max_length=16,
                verbose_name="HEX color of the node in graph canvas",
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="position_x",
            field=models.FloatField(
                default=0.0, help_text="x-Position in graph canvas"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="position_y",
            field=models.FloatField(
                default=0.0, help_text="y-Position in graph canvas"
            ),
        ),
    ]
