# Generated by Django 4.1.3 on 2022-12-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0003_node_color_node_position_x_node_position_y"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scriptcell",
            options={"ordering": ["node", "cell_order", "uuid"]},
        ),
        migrations.AlterUniqueTogether(
            name="scriptcell",
            unique_together=set(),
        ),
    ]
