# Generated by Django 4.1.3 on 2022-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0004_alter_scriptcell_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scriptcell",
            name="cell_type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown"),
                    ("python", "Python"),
                    ("supercollider", "SuperCollider"),
                    ("comment", "Comment"),
                ],
                default="comment",
                max_length=128,
                verbose_name="Cell type",
            ),
        ),
    ]
