# Generated by Django 4.1.3 on 2023-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0005_alter_scriptcell_cell_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_entry_node",
            field=models.BooleanField(
                default=False,
                help_text="Acts as a singular entrypoint for our graph.Only one such node can exist per graph.",
                verbose_name="Is Entry node?",
            ),
        ),
        migrations.AddConstraint(
            model_name="node",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_entry_node", True)),
                fields=("graph",),
                name="unique_entry_point",
            ),
        ),
    ]
