# Generated by Django 4.1.3 on 2023-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0006_node_is_entry_node_node_unique_entry_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="graph",
            name="stream_assignment_policy",
            field=models.CharField(
                choices=[
                    ("one_graph_one_stream", "Each graph has only one stream"),
                    ("one_user_one_stream", "Each user gets its own stream"),
                    ("deactivate", "No stream assignment"),
                ],
                default="one_user_one_stream",
                help_text="Manages the stream assignment for this graph",
                max_length=255,
            ),
        ),
    ]
