# Generated by Django 4.1.3 on 2023-03-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0007_graph_stream_assignment_policy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GraphSession",
        ),
    ]
