# Generated by Django 4.1.3 on 2023-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_graph", "0010_scriptcell_audio_type_needs_audio_cell_information"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="graph",
            options={
                "ordering": ["name"],
                "verbose_name": "Graph",
                "verbose_name_plural": "Graphs",
            },
        ),
        migrations.AddField(
            model_name="node",
            name="is_blocking_node",
            field=models.BooleanField(
                default=False,
                help_text="If we encounter this node during graph execution we will halt execution indefinitely on this node. This is useful if we have setup a state and do not want to change it anymore.",
                verbose_name="Is blocking node?",
            ),
        ),
    ]
