# Generated by Django 4.1.3 on 2023-08-10 16:17

from django.db import migrations, models


def change_drifter_to_default_template(apps, schema_editor):
    Graph = apps.get_model("story_graph", "Graph")
    Graph.objects.filter(template_name="drifter").update(template_name="default")


class Migration(migrations.Migration):
    dependencies = [
        ("story_graph", "0014_make_slug_unique"),
    ]

    operations = [
        migrations.RunPython(
            code=change_drifter_to_default_template,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="graph",
            name="about_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text about the graph which can be accessed during a stream - only if this is set",
                verbose_name="About text (markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="end_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text which will be displayed at the end of a stream",
                verbose_name="End text (markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="slug_name",
            field=models.SlugField(
                help_text="Will be used as a URL",
                max_length=256,
                unique=True,
                verbose_name="Slug name",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="start_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Text about the graph which will be displayed at the start of a stream - only if this is set",
                verbose_name="Start text (markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="graph",
            name="template_name",
            field=models.CharField(
                choices=[("default", "Default template")],
                default="default",
                help_text="Allows to switch to a different template in the frontend with different connection flows or UI",
                max_length=255,
                verbose_name="Frontend template",
            ),
        ),
    ]
