name: 'Upload test results'
on:
  workflow_run:
    workflows: ['run-tests']                     # runs after CI workflow
    types:
      - completed

jobs:
  upload-report:
    runs-on: ubuntu-20.04
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Unit tests                  # Name of the check run which will be created
        path: 'tests.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test results
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: MyPy tests                  # Name of the check run which will be created
        path: 'mypy-tests.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit              # Format of test
